### ISSUE TITLE
Bot stops working after a large number of messages in a channel. It simply won't work regardless of how many times I tried. The bot also take more time to load the more messages it have transferred. 

### ISSUE THREAD

**Issue by Potatococ** [BilliAlpha/discord-transfer#17]
2023-01-27 23:59:41 INFO  com.billialpha.discord.transfer.DiscordTransfer - Logging in ...
2023-01-27 23:59:48 INFO  com.billialpha.discord.transfer.DiscordTransfer - Logged in, user: Migrator#6340
2023-01-27 23:59:49 INFO  com.billialpha.discord.transfer.DiscordTransfer - Loaded source guild: 
2023-01-27 23:59:49 INFO  com.billialpha.discord.transfer.DiscordTransfer - Loaded dest guild:
2023-01-27 23:59:49 INFO  com.billialpha.discord.transfer.DiscordTransfer - Start action 'migrate'
2023-01-27 23:59:49 INFO  com.billialpha.discord.transfer.DiscordTransfer - Starting migration ...
2023-01-27 23:59:49 INFO  com.billialpha.discord.transfer.DiscordTransfer - Migrating category: 
2023-01-27 23:59:49 INFO  com.billialpha.discord.transfer.DiscordTransfer - Migrating channel: 
2023-01-28 00:17:39 WARN  com.billialpha.discord.transfer.DiscordTransfer - Error in channel migration
java.net.UnknownHostException: Failed to resolve 'discord.com' after 4 queries
        at io.netty.resolver.dns.DnsResolveContext.finishResolve(DnsResolveContext.java:1047)
        Suppressed: reactor.core.publisher.FluxOnAssembly$OnAssemblyException:
Error has been observed at the following site(s):
        *__checkpoint ? Request to GET /channels/834237787053490187/messages [RequestStream]
        *__checkpoint ? Request to GET /channels/834237787053490187/messages [DefaultRouter]
Original Stack Trace:
                at io.netty.resolver.dns.DnsResolveContext.finishResolve(DnsResolveContext.java:1047)
                at io.netty.resolver.dns.DnsResolveContext.tryToFinishResolve(DnsResolveContext.java:1000)
                at io.netty.resolver.dns.DnsResolveContext.query(DnsResolveContext.java:418)
                at io.netty.resolver.dns.DnsResolveContext.access$600(DnsResolveContext.java:66)
                at io.netty.resolver.dns.DnsResolveContext$2.operationComplete(DnsResolveContext.java:467)
                at io.netty.util.concurrent.DefaultPromise.notifyListener0(DefaultPromise.java:578)
                at io.netty.util.concurrent.DefaultPromise.notifyListeners0(DefaultPromise.java:571)
                at io.netty.util.concurrent.DefaultPromise.notifyListenersNow(DefaultPromise.java:550)
                at io.netty.util.concurrent.DefaultPromise.notifyListeners(DefaultPromise.java:491)
                at io.netty.util.concurrent.DefaultPromise.setValue0(DefaultPromise.java:616)
                at io.netty.util.concurrent.DefaultPromise.setFailure0(DefaultPromise.java:609)
                at io.netty.util.concurrent.DefaultPromise.tryFailure(DefaultPromise.java:117)
                at io.netty.resolver.dns.DnsQueryContext.tryFailure(DnsQueryContext.java:256)
                at io.netty.resolver.dns.DnsQueryContext$4.run(DnsQueryContext.java:208)
                at io.netty.util.concurrent.PromiseTask.runTask(PromiseTask.java:98)
                at io.netty.util.concurrent.ScheduledFutureTask.run(ScheduledFutureTask.java:153)
                at io.netty.util.concurrent.AbstractEventExecutor.runTask(AbstractEventExecutor.java:174)
                at io.netty.util.concurrent.AbstractEventExecutor.safeExecute(AbstractEventExecutor.java:167)
                at io.netty.util.concurrent.SingleThreadEventExecutor.runAllTasks(SingleThreadEventExecutor.java:470)
                at io.netty.channel.nio.NioEventLoop.run(NioEventLoop.java:503)
                at io.netty.util.concurrent.SingleThreadEventExecutor$4.run(SingleThreadEventExecutor.java:997)
                at io.netty.util.internal.ThreadExecutorMap$2.run(ThreadExecutorMap.java:74)
                at io.netty.util.concurrent.FastThreadLocalRunnable.run(FastThreadLocalRunnable.java:30)
                at java.base/java.lang.Thread.run(Thread.java:834)
Caused by: io.netty.resolver.dns.DnsNameResolverTimeoutException: [/127.0.2.3:53] query via UDP timed out after 5000 milliseconds (no stack trace available)
2023-01-28 00:17:39 INFO  com.billialpha.discord.transfer.DiscordTransfer - Migration finished successfully (null messages)
2023-01-28 00:17:39 INFO  com.billialpha.discord.transfer.DiscordTransfer - Logged out

**Comment by BilliAlpha** [comment]
I'm pretty sure the issue is on your side here.
Do you have a reliable internet connection ?
Have you tried on another network ?

**Comment by Potatococ** [comment]
I did try on multiple networks previously.

**Comment by Berryyyyy** [comment]
> I'm pretty sure the issue is on your side here. Do you have a reliable internet connection ? Have you tried on another network ?

hey do you have discord where i can contact you?

**Comment by BilliAlpha** [comment]
@Berryyyyy Could you please open a new issue with your specific problem ?

**Comment by BilliAlpha** [comment]
@Potatococ Are you still facing the issue ?

**Comment by Potatococ** [comment]
yes, on windows, not sure in mac but im about to try it if it's possible
